### ISSUE TITLE
Update to 1.0.17

### ISSUE THREAD

**Issue by taaem** [flathub/com.github.xournalpp.xournalpp#15] opened 2020-02-18 16:48 UTC
There was a minor release 1.0.17, it would be awesome if the flatpak could be updated.

**Comment by muelli** [comment] 2020-02-18 18:20
https://github.com/flathub/com.github.xournalpp.xournalpp/pull/16

something seems to be off with the build system.
https://flathub.org/builds/#/builders/48/builds/1787
```
-- Installing: /app/share/mime/packages/com.github.xournalpp.xournalpp.xml
-- Installing: /app/share/applications/com.github.xournalpp.xournalpp.desktop
-- Installing: /app/share/mimelnk/application/x-xojpp.desktop
-- Installing: /app/share/mimelnk/application/x-xopp.desktop
-- Installing: /app/share/mimelnk/application/x-xopt.desktop
-- Installing: /app/share/thumbnailers/com.github.xournalpp.xournalpp.thumbnailer
-- Installing: /app/share/metainfo/com.github.xournalpp.xournalpp.appdata.xml
CMake Error at po/cmake_install.cmake:41 (file):
  file INSTALL cannot find "/run/build/xournalpp/po/cs.gmo".
Call Stack (most recent call first):
  cmake_install.cmake:102 (include)
FAILED: CMakeFiles/install.util 
cd /run/build/xournalpp && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

Maybe @Technius knows more.

**Comment by Technius** [comment] 2020-02-18 18:55
There was a regression in 1.0.17 that causes fresh install targets to fail. As a workaround, you'll need to insert the following command before building the package, either through a patch or by changing the manifest:
```
cmake --build . --target translations
```
This bug has already been fixed in master branch.

**Comment by muelli** [comment] 2020-02-19 07:40
For me, either a patch (i.e. a specific commit exported with git format-patch) or, better yet, a new minor release would be easiest. Can you provide any of those?

**Comment by Technius** [comment] 2020-02-20 04:15
Here's the commit (note: it's on master branch) that fixed the bug: https://github.com/xournalpp/xournalpp/commit/12387b01a1c7e529580c6f27e92dad3e8b4f9858

Making another release takes a non-trivial amount of work, and there aren't enough changes yet to justify another one.

I looked into a manifest-only solution just now. It seems like it might build if you add a `build-commands` section with `cmake --build . --target translations` here:
https://github.com/flathub/com.github.xournalpp.xournalpp/pull/16/files#diff-401bf316052643a8442c37858dc47da1L100

**Comment by muelli** [comment] 2020-02-20 09:05
nah. Then I'd need to change the buildsystem to "simple" and be responsible for calling cmake and ninja in the appropriate ways. I'd rather not modify the call to cmake and import the patch.

The patch, however, [does not seem to work](https://flathub.org/builds/#/builders/10/builds/1819):
```
ninja: error: dependency cycle: po/cs.po -> po/cs.po
```

I guess we're better off waiting for a release that can be built.

Reg. making a new release: You know best, of course, what it takes. I'd argue that fixing a broken release, which can't be used by downstreams anyway, is big enough of a change to warrant a release ;-)

**Comment by Technius** [comment] 2020-02-22 18:08
The build needs to be out-of-tree (set `builddir: true`).

**Comment by muelli** [comment] 2020-03-16 11:58
https://github.com/flathub/com.github.xournalpp.xournalpp/pull/16 has been merged

**Closed by muelli** 2020-03-16 11:58 UTC
